services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackshelf
    ports:
      - "5433:5432"   # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
